name: 02 - Workflow Events

on:
  # When you have triggers that require configuration (like schedule with cron), you can't mix array-style syntax (- push) with mapping-style syntax. 
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Workflow triggered by ${{ github.event_name }} event"