name: 17 - 2 - Custom Actions - JS

on: 
  workflow_dispatch:

run-name: "Run 17 - 2 - Custom Actions - JS"

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Check for dependency updates"
        uses: ./.github/actions/js-dependency-update