name: 17 - 3 - Custom Actions - Docker

on: 
  workflow_dispatch:
    inputs:
      url:
        description: "The URL to ping"
        default: "https://www.google.com"
        required: true
      max_trials:
        description: "Maximum number of ping attempts"
        default: '10'
        required: false
      delay_seconds:
        description: "Delay between ping attempts in seconds"
        default: '5'
        required: false

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Ping URL using custom Docker action"
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ github.event.inputs.url }}
          max-trials: ${{ github.event.inputs.max_trials }}
          delay-seconds: ${{ github.event.inputs.delay_seconds }}