name: 17 - 3 - Custom Actions - Docker

on: 
  workflow_dispatch:
    inputs:
      url:
        description: "The URL to ping"
        default: "https://www.google.com"
        required: true

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Ping URL using custom Docker action"
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ github.event.inputs.url }}